/*globals define, _*/
/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './DiagramDesigner/PetriNetDecorator.DiagramDesignerWidget',
    './PartBrowser/PetriNetDecorator.PartBrowserWidget'
], function (DecoratorBase, PetriNetDecoratorDiagramDesignerWidget, PetriNetDecoratorPartBrowserWidget) {

    'use strict';

    var DECORATOR_ID = 'PetriNetDecorator';

    function PetriNetDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('PetriNetDecorator ctor');
    }

    _.extend(PetriNetDecorator.prototype, DecoratorBase.prototype);
    PetriNetDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    PetriNetDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            DiagramDesigner: PetriNetDecoratorDiagramDesignerWidget,
            PartBrowser: PetriNetDecoratorPartBrowserWidget
        };
    };

    return PetriNetDecorator;
});
